apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3 # Increase the number of replicas to enable load balancing
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: europe-west1-docker.pkg.dev/agisit-2425-website-98956/frontend-repo/frontend-image:latest
        ports:
        - containerPort: 3000
