{
 "title": "Prometheus Metrics Dashboard",
 "tags": [ "prometheus" ],
 "panels": [
  {
   "title": "CPU Usage Rate",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='default'}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace='default'}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Network Traffic Rate(Bytes)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace='default'}[5m])) by (pod)",
     "legendFormat": "{{ pod }} Receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace='default'}[5m])) by (pod)",
     "legendFormat": "{{ pod }} Transmit"
    }
   ]
  },
  {
   "title": "Requests Rate per second",
   "type": "graph",
   "gridPos": { "x": 0, "y": 32, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=~\"frontend-job|history-job|play-computer-job|play-player-job\"}[5m])) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Request Latency average",
   "type": "graph",
   "gridPos": { "x": 0, "y": 40, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "avg(http_request_latency_seconds{job=~\"frontend-job|history-job|play-computer-job|play-player-job\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}