apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
      - name: history
        image: europe-west1-docker.pkg.dev/agisit-2425-website-98956/backend-repo/history-image:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE_NAME
          value: "tictactoe"
        - name: DATABASE_HOST
          value: "postgres-service"  # The name of the PostgreSQL service in Kubernetes
        - name: DATABASE_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: history-service
spec:
  type: ClusterIP
  selector:
    app: history
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
